// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd4RVWUBGovDmN7YfHsANgIWcb12arNgM',
    appId: '1:862135583895:web:ade7c29a7cad50f59955d2',
    messagingSenderId: '862135583895',
    projectId: 'wordfinder-99bb6',
    authDomain: 'wordfinder-99bb6.firebaseapp.com',
    storageBucket: 'wordfinder-99bb6.appspot.com',
    measurementId: 'G-KJ8GCMEECX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPIYizsvfVAna5NZzFniWfgkKhNdm_L-8',
    appId: '1:862135583895:android:f1e665b8ff48e28b9955d2',
    messagingSenderId: '862135583895',
    projectId: 'wordfinder-99bb6',
    storageBucket: 'wordfinder-99bb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYRa4Y8tWwsT3Kct-uPjoXcAkckgI_Q9U',
    appId: '1:862135583895:ios:167be1bc1a0af6ee9955d2',
    messagingSenderId: '862135583895',
    projectId: 'wordfinder-99bb6',
    storageBucket: 'wordfinder-99bb6.appspot.com',
    iosClientId: '862135583895-02b7o96dqechhb2ub3aksa1l94pu3coj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionaryApi',
  );
}
